use anyhow::{Context, Result};
use clap::Args;
use latticefs_base::LatticeRepo;
use latticefs_base::Permission;
use std::io::{self, Write};

use super::common::parse_ref_with_version;
use latticefs_base::is_quarantined_executable;

#[derive(Args, Debug)]
pub struct CatArgs {
    /// Object reference (optionally @version)
    pub reference: String,
}

pub async fn run(repo: LatticeRepo, args: CatArgs) -> Result<()> {
    let (object_id, version_id) = parse_ref_with_version(&repo, &args.reference)?;

    let object = repo
        .metadata
        .load_object(&object_id)
        .with_context(|| format!("Object not found: {}", object_id))?;
    repo.authorize_object_permission(&object, Permission::Read, false)?;
    let version = match version_id {
        Some(v) => repo.metadata.load_version(&v)?,
        None => repo.metadata.load_version(&object.current_version)?,
    };

    if is_quarantined_executable(&object.tags) {
        return Err(anyhow::anyhow!("Object is quarantined and executable"));
    }

    let manifest = repo.metadata.load_manifest(&version.manifest_ref)?;
    let data = repo.chunks.retrieve_object(&manifest).await?;

    let mut stdout = io::stdout();
    stdout.write_all(&data)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use latticefs_base::model::{Object, ObjectID, ObjectType, Tag, Version, VersionID};
    use tempfile::TempDir;

    fn test_actor() -> [u8; 32] {
        [0u8; 32]
    }

    // Helper to create a test object with data
    async fn create_test_object_with_data(
        repo: &LatticeRepo,
        data: &[u8],
        tags: Vec<Tag>,
    ) -> Result<(ObjectID, VersionID)> {
        let manifest = repo.store_object_data(data).await?;
        let manifest_ref = repo.metadata.store_manifest(&manifest)?;

        let object_id = ObjectID::new();
        let chunk_root = manifest.merkle_root;

        let version = Version::new(
            object_id,
            None,
            chunk_root,
            manifest_ref,
            test_actor(),
            data.len() as u64,
            manifest.chunks.len() as u32,
            None,
        );

        // Use the version ID that was generated by Version::new()
        let version_id = version.id;

        let mut object = Object::new(ObjectType::Blob, version_id, test_actor());
        object.id = object_id;
        for tag in tags {
            object.add_tag(tag);
        }

        repo.metadata.store_object(&object)?;
        repo.metadata.store_version(&version)?;

        Ok((object_id, version_id))
    }

    // Helper to retrieve object data (replicates cat logic without stdout)
    async fn retrieve_object_data(repo: &LatticeRepo, reference: &str) -> Result<Vec<u8>> {
        let (object_id, version_id) = parse_ref_with_version(repo, reference)?;
        let object = repo.metadata.load_object(&object_id)?;
        let version = match version_id {
            Some(v) => repo.metadata.load_version(&v)?,
            None => repo.metadata.load_version(&object.current_version)?,
        };
        let manifest = repo.metadata.load_manifest(&version.manifest_ref)?;
        repo.chunks
            .retrieve_object(&manifest)
            .await
            .map_err(|e| anyhow::anyhow!("Failed to retrieve object: {}", e))
    }

    #[tokio::test]
    async fn test_cat_success_current_version() {
        let temp = TempDir::new().unwrap();
        let repo = LatticeRepo::open_at(temp.path()).unwrap();

        let test_data = b"Hello, LatticeFS!";
        let (object_id, _version_id) = create_test_object_with_data(&repo, test_data, vec![])
            .await
            .unwrap();

        let args = CatArgs {
            reference: object_id.to_string(),
        };

        // Test that the function succeeds
        let result = run(repo, args).await;
        assert!(result.is_ok());
    }

    #[tokio::test]
    async fn test_cat_success_specific_version() {
        let temp = TempDir::new().unwrap();
        let repo = LatticeRepo::open_at(temp.path()).unwrap();

        let test_data = b"Version 1";
        let (object_id, version_id) = create_test_object_with_data(&repo, test_data, vec![])
            .await
            .unwrap();

        // Create a second version
        let test_data2 = b"Version 2";
        let manifest = repo.store_object_data(test_data2).await.unwrap();
        let manifest_ref = repo.metadata.store_manifest(&manifest).unwrap();
        let mut object = repo.metadata.load_object(&object_id).unwrap();
        let version2 = Version::new(
            object_id,
            Some(version_id),
            manifest.merkle_root,
            manifest_ref,
            test_actor(),
            test_data2.len() as u64,
            manifest.chunks.len() as u32,
            None,
        );
        object.add_version(version2.id);
        repo.metadata.store_version(&version2).unwrap();
        repo.metadata.store_object(&object).unwrap();

        let args = CatArgs {
            reference: format!("{}@v1", object_id),
        };

        // Test that the function succeeds for specific version
        let result = run(repo, args).await;
        assert!(result.is_ok());
    }

    #[tokio::test]
    async fn test_cat_object_not_found() {
        let temp = TempDir::new().unwrap();
        let repo = LatticeRepo::open_at(temp.path()).unwrap();

        let fake_id = ObjectID::new();
        let args = CatArgs {
            reference: fake_id.to_string(),
        };

        let result = run(repo, args).await;
        assert!(result.is_err());
        assert!(result
            .unwrap_err()
            .to_string()
            .contains("Object not found"));
    }

    #[tokio::test]
    async fn test_cat_invalid_reference() {
        let temp = TempDir::new().unwrap();
        let repo = LatticeRepo::open_at(temp.path()).unwrap();

        let args = CatArgs {
            reference: "invalid-reference".to_string(),
        };

        let result = run(repo, args).await;
        assert!(result.is_err());
    }

    #[tokio::test]
    async fn test_cat_quarantined_executable() {
        let temp = TempDir::new().unwrap();
        let repo = LatticeRepo::open_at(temp.path()).unwrap();

        let test_data = b"#!/bin/bash\necho hello";
        let tags = vec![
            Tag::new("auto:executable".to_string(), "true".to_string(), test_actor()),
            Tag::new("sys:trust".to_string(), "50".to_string(), test_actor()), // < 90
        ];
        let (object_id, _version_id) = create_test_object_with_data(&repo, test_data, tags)
            .await
            .unwrap();

        let args = CatArgs {
            reference: object_id.to_string(),
        };

        let result = run(repo, args).await;
        assert!(result.is_err());
        assert!(result
            .unwrap_err()
            .to_string()
            .contains("quarantined and executable"));
    }

    #[tokio::test]
    async fn test_cat_executable_with_high_trust() {
        let temp = TempDir::new().unwrap();
        let repo = LatticeRepo::open_at(temp.path()).unwrap();

        let test_data = b"#!/bin/bash\necho hello";
        let tags = vec![
            Tag::new("auto:executable".to_string(), "true".to_string(), test_actor()),
            Tag::new("sys:trust".to_string(), "95".to_string(), test_actor()), // >= 90
        ];
        let (object_id, _version_id) = create_test_object_with_data(&repo, test_data, tags)
            .await
            .unwrap();

        let args = CatArgs {
            reference: object_id.to_string(),
        };

        // Should succeed because trust >= 90
        let result = run(repo, args).await;
        assert!(result.is_ok());
    }

    #[tokio::test]
    async fn test_cat_version_not_found() {
        let temp = TempDir::new().unwrap();
        let repo = LatticeRepo::open_at(temp.path()).unwrap();

        let test_data = b"Hello";
        let (object_id, _version_id) = create_test_object_with_data(&repo, test_data, vec![])
            .await
            .unwrap();

        let fake_version_id = VersionID::new();
        let args = CatArgs {
            reference: format!("{}@{}", object_id, fake_version_id),
        };

        let result = run(repo, args).await;
        assert!(result.is_err());
    }

    #[tokio::test]
    async fn test_cat_retrieves_correct_data() {
        let temp = TempDir::new().unwrap();
        let repo = LatticeRepo::open_at(temp.path()).unwrap();

        let test_data = b"Test data content";
        let (object_id, _version_id) = create_test_object_with_data(&repo, test_data, vec![])
            .await
            .unwrap();

        // Verify we can retrieve the data correctly
        let retrieved = retrieve_object_data(&repo, &object_id.to_string()).await.unwrap();
        assert_eq!(retrieved, test_data);
    }

    #[tokio::test]
    async fn test_cat_with_version_alias() {
        let temp = TempDir::new().unwrap();
        let repo = LatticeRepo::open_at(temp.path()).unwrap();

        let test_data1 = b"First version";
        let (object_id, version1_id) = create_test_object_with_data(&repo, test_data1, vec![])
            .await
            .unwrap();

        // Create second version
        let test_data2 = b"Second version";
        let manifest = repo.store_object_data(test_data2).await.unwrap();
        let manifest_ref = repo.metadata.store_manifest(&manifest).unwrap();
        let mut object = repo.metadata.load_object(&object_id).unwrap();
        let version2 = Version::new(
            object_id,
            Some(version1_id),
            manifest.merkle_root,
            manifest_ref,
            test_actor(),
            test_data2.len() as u64,
            manifest.chunks.len() as u32,
            None,
        );
        object.add_version(version2.id);
        repo.metadata.store_version(&version2).unwrap();
        repo.metadata.store_object(&object).unwrap();

        // Test with v1 alias
        let retrieved = retrieve_object_data(&repo, &format!("{}@v1", object_id)).await.unwrap();
        assert_eq!(retrieved, test_data1);
    }
}
