// This file is @generated by prost-build.
/// Timestamp (Unix microseconds)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Timestamp {
    #[prost(int64, tag = "1")]
    pub micros: i64,
}
/// Object identifier
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ObjectId {
    /// 16 bytes (UUID)
    #[prost(bytes = "vec", tag = "1")]
    pub uuid: ::prost::alloc::vec::Vec<u8>,
}
/// Version identifier
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VersionId {
    #[prost(bytes = "vec", tag = "1")]
    pub uuid: ::prost::alloc::vec::Vec<u8>,
}
/// Content hash (BLAKE3)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Hash {
    /// 32 bytes
    #[prost(bytes = "vec", tag = "1")]
    pub blake3: ::prost::alloc::vec::Vec<u8>,
}
/// Error message
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Error {
    #[prost(uint32, tag = "1")]
    pub code: u32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "3")]
    pub details: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
/// Share request: Create capability for object
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ShareRequest {
    #[prost(message, optional, tag = "1")]
    pub object_id: ::core::option::Option<ObjectId>,
    /// did:key:...
    #[prost(string, tag = "2")]
    pub audience_did: ::prost::alloc::string::String,
    /// "read", "write", etc.
    #[prost(string, tag = "3")]
    pub capability: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub expires_at: ::core::option::Option<Timestamp>,
    /// Optional constraints
    #[prost(map = "string, string", tag = "5")]
    pub facts: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ShareResponse {
    #[prost(oneof = "share_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<share_response::Result>,
}
/// Nested message and enum types in `ShareResponse`.
pub mod share_response {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        /// Success: UCAN token
        #[prost(string, tag = "1")]
        UcanToken(::prost::alloc::string::String),
        /// Failure
        #[prost(message, tag = "2")]
        Error(super::Error),
    }
}
/// Revoke request: Invalidate capability
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RevokeRequest {
    /// CID of UCAN to revoke
    #[prost(string, tag = "1")]
    pub ucan_cid: ::prost::alloc::string::String,
    /// Optional
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RevokeResponse {
    #[prost(oneof = "revoke_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<revoke_response::Result>,
}
/// Nested message and enum types in `RevokeResponse`.
pub mod revoke_response {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(bool, tag = "1")]
        Success(bool),
        #[prost(message, tag = "2")]
        Error(super::Error),
    }
}
/// Fetch request: Retrieve object via UCAN
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FetchRequest {
    #[prost(message, optional, tag = "1")]
    pub object_id: ::core::option::Option<ObjectId>,
    #[prost(string, tag = "2")]
    pub ucan_token: ::prost::alloc::string::String,
    /// Specific version, or latest
    #[prost(message, optional, tag = "3")]
    pub version_id: ::core::option::Option<VersionId>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FetchResponse {
    #[prost(oneof = "fetch_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<fetch_response::Result>,
}
/// Nested message and enum types in `FetchResponse`.
pub mod fetch_response {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Data(super::ObjectData),
        #[prost(message, tag = "2")]
        Error(super::Error),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ObjectData {
    #[prost(message, optional, tag = "1")]
    pub object_id: ::core::option::Option<ObjectId>,
    #[prost(message, optional, tag = "2")]
    pub version_id: ::core::option::Option<VersionId>,
    /// Object content
    #[prost(bytes = "vec", tag = "3")]
    pub content: ::prost::alloc::vec::Vec<u8>,
    #[prost(map = "string, string", tag = "4")]
    pub metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(message, repeated, tag = "5")]
    pub tags: ::prost::alloc::vec::Vec<Tag>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Tag {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
}
/// Sync event: Notify of graph changes
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncEvent {
    #[prost(message, optional, tag = "1")]
    pub timestamp: ::core::option::Option<Timestamp>,
    /// "object_created", "version_added", etc.
    #[prost(string, tag = "2")]
    pub event_type: ::prost::alloc::string::String,
    /// Event-specific data
    #[prost(bytes = "vec", tag = "3")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ObjectCreatedEvent {
    #[prost(message, optional, tag = "1")]
    pub object_id: ::core::option::Option<ObjectId>,
    #[prost(message, optional, tag = "2")]
    pub version_id: ::core::option::Option<VersionId>,
    #[prost(string, tag = "3")]
    pub actor_did: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VersionAddedEvent {
    #[prost(message, optional, tag = "1")]
    pub object_id: ::core::option::Option<ObjectId>,
    #[prost(message, optional, tag = "2")]
    pub version_id: ::core::option::Option<VersionId>,
    #[prost(message, optional, tag = "3")]
    pub parent_version: ::core::option::Option<VersionId>,
    #[prost(string, tag = "4")]
    pub actor_did: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TagAddedEvent {
    #[prost(message, optional, tag = "1")]
    pub object_id: ::core::option::Option<ObjectId>,
    #[prost(message, optional, tag = "2")]
    pub tag: ::core::option::Option<Tag>,
    #[prost(string, tag = "3")]
    pub actor_did: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LinkCreatedEvent {
    #[prost(message, optional, tag = "1")]
    pub source: ::core::option::Option<ObjectId>,
    #[prost(message, optional, tag = "2")]
    pub target: ::core::option::Option<ObjectId>,
    #[prost(string, tag = "3")]
    pub link_type: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub actor_did: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncAck {
    #[prost(message, optional, tag = "1")]
    pub event_timestamp: ::core::option::Option<Timestamp>,
    #[prost(bool, tag = "2")]
    pub success: bool,
}
/// Status request: Get system status
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatusRequest {
    #[prost(bool, tag = "1")]
    pub include_stats: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatusResponse {
    #[prost(string, tag = "1")]
    pub version: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub running: bool,
    #[prost(message, optional, tag = "3")]
    pub stats: ::core::option::Option<Stats>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Stats {
    #[prost(uint64, tag = "1")]
    pub total_objects: u64,
    #[prost(uint64, tag = "2")]
    pub total_versions: u64,
    #[prost(uint64, tag = "3")]
    pub total_chunks: u64,
    #[prost(uint64, tag = "4")]
    pub storage_bytes: u64,
    /// E.g., 150 = 1.5x
    #[prost(uint64, tag = "5")]
    pub dedup_ratio_x100: u64,
}
/// Shutdown request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ShutdownRequest {
    #[prost(bool, tag = "1")]
    pub force: bool,
    #[prost(uint32, tag = "2")]
    pub timeout_seconds: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ShutdownResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
}
/// Watch register request: Register a file for watching
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WatchRegisterRequest {
    #[prost(string, tag = "1")]
    pub temp_path: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub object_id: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub actor_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "4")]
    pub content_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "5")]
    pub display_name: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WatchRegisterResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// Watch unregister request: Stop watching a file
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WatchUnregisterRequest {
    #[prost(string, tag = "1")]
    pub temp_path: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WatchUnregisterResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// Watch list request: List all watched files
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WatchListRequest {}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WatchListResponse {
    #[prost(message, repeated, tag = "1")]
    pub files: ::prost::alloc::vec::Vec<WatchedFileInfo>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WatchedFileInfo {
    #[prost(string, tag = "1")]
    pub temp_path: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub object_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub display_name: ::prost::alloc::string::String,
    #[prost(int64, tag = "4")]
    pub registered_at: i64,
}
/// Watch status request: Get watcher daemon status
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WatchStatusRequest {}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WatchStatusResponse {
    #[prost(bool, tag = "1")]
    pub running: bool,
    #[prost(uint64, tag = "2")]
    pub watched_count: u64,
    #[prost(string, tag = "3")]
    pub watch_dir: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    pub pid: u64,
}
